### ISSUE TITLE
✨[FEAT] 보관함 기능 구현하기

### ISSUE THREAD

**Issue by lenamin** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#4]
## 💡 Issue
보관함 모달뷰의 기능을 구현합니다. 

### 보관함 사이드바 관련 task
- [ ] 폴더 편집 기능 -> 폴더별로 `삭제`, `정보` 버튼 나타내기 
- [ ] 폴더 추가 기능 -> 폴더를 추가하기 위한 모달화면 띄우기 
- [ ] 폴더 삭제 기능 -> `삭제` 탭하면 alert 띄우기, swipe 를 통한 삭제 기능 구현하기 

### 보관함 선택 기능 관련 task
- [ ] 툴 선택하면 툴 테두리 활성화되는 기능 구현하기
- [ ] 툴 선택하면 버튼이 활성화되는 기능 구현하기
- [ ] 추가, 삭제, 폴더이동, 다중선택 기능 구현하기

**Comment by compuTasha** [comment]
p2;
보관함 선택 기능 관련 task는 새로운 이슈로 파고 요 이슈는 보관함 사이드바 기능 구현하기로 변경하는 건 어떨까요?!

**Comment by lenamin** [comment]
업무분장 변경으로 현재 이슈는 닫았습니다!
